version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: mirae-user
      POSTGRES_PASSWORD: mirae-password
      POSTGRES_DB: mirae
    ports:
      - "5437:5432"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 3s
      retries: 3