### POST Request - Menambahkan data saham baru
POST http://localhost:8080/api/v1/stock
Content-Type: application/json

{
    "name": "Mahaka Media Tbk.",
    "code": "ABBX",
    "price": 500,
    "frequency": 1,
    "volume": 1200
}

###

### GET Request - Mendapatkan semua data saham
GET http://localhost:8080/api/v1/stock
Content-Type: application/json

###

### GET Request - Mendapatkan detail saham
GET http://localhost:8080/api/v1/stock/1
Content-Type: application/json

###

### PUT Request - Update data  saham
PUT http://localhost:8080/api/v1/stock/1
Content-Type: application/json

{
    "name": "Mahaka Media Tbk.",
    "code": "ABBA",
    "price": 2000000,
    "frequency": 1,
    "volume": 10000
}

###

### DELETE Request - Delete data  saham
DELETE http://localhost:8080/api/v1/stock/1
Content-Type: application/json

###